### ISSUE TITLE
Possible bug in infernal descriptions

### ISSUE THREAD

**Issue by rdfinn** [ProteinsWebTeam/ebi-metagenomics-cwl#23]
In the infernal description, it refers to "spades" in the specs - should this not be cmscan?
```
hints:
  - $import: infernal-docker.yml
  - class: SoftwareRequirement
    packages:
      spades:
        specs: [ "https://identifiers.org/rrid/RRID:SCR_011809" ]
        version: [ "1.1.2" ]
```

https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/infernal-cmscan.cwl
